// esbuild build for the Birko.Web Playground.
//
// Bundles src/app.ts -> wwwroot/app.js and copies the Birko base CSS into wwwroot/css/.
// Resolves the Birko.Web.* TypeScript sources from the Birko\Web bucket WITHOUT a
// machine-specific path: prefer the BIRKO_SRC env var (CI/Docker), otherwise walk up
// from this file to find the Birko/Web checkout. Safe to commit.
import * as esbuild from 'esbuild';
import { existsSync, mkdirSync, copyFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function resolveBirkoWeb() {
  const env = process.env.BIRKO_SRC;
  if (env) return env.replace(/[\\/]+$/, '').replaceAll('\\', '/');
  for (let d = __dirname; d !== dirname(d); d = dirname(d)) {
    const c = resolve(d, 'Birko/Web');
    if (existsSync(resolve(c, 'Birko.Web.Core'))) return c.replaceAll('\\', '/');
  }
  throw new Error('Cannot locate Birko\\Web. Set the BIRKO_SRC env var to its path.');
}

const BIRKO_SRC = resolveBirkoWeb();
const WATCH = process.argv.includes('--watch');

const aliases = {
  'birko-web-core':          `${BIRKO_SRC}/Birko.Web.Core/src/index.ts`,
  'birko-web-core/base':     `${BIRKO_SRC}/Birko.Web.Core/src/base/index.ts`,
  'birko-web-core/state':    `${BIRKO_SRC}/Birko.Web.Core/src/state/index.ts`,
  'birko-web-core/http':     `${BIRKO_SRC}/Birko.Web.Core/src/http/index.ts`,
  'birko-web-core/router':   `${BIRKO_SRC}/Birko.Web.Core/src/router/index.ts`,
  'birko-web-core/i18n':     `${BIRKO_SRC}/Birko.Web.Core/src/i18n/index.ts`,
  'birko-web-core/offline':  `${BIRKO_SRC}/Birko.Web.Core/src/offline/index.ts`,
  'birko-web-components':            `${BIRKO_SRC}/Birko.Web.Components/src/index.ts`,
  'birko-web-components/inputs':     `${BIRKO_SRC}/Birko.Web.Components/src/inputs/index.ts`,
  'birko-web-components/layout':     `${BIRKO_SRC}/Birko.Web.Components/src/layout/index.ts`,
  'birko-web-components/data':       `${BIRKO_SRC}/Birko.Web.Components/src/data/index.ts`,
  'birko-web-components/feedback':   `${BIRKO_SRC}/Birko.Web.Components/src/feedback/index.ts`,
  'birko-web-components/nav':        `${BIRKO_SRC}/Birko.Web.Components/src/nav/index.ts`,
  'birko-web-components/command':    `${BIRKO_SRC}/Birko.Web.Components/src/command/index.ts`,
  'birko-web-components/form-utils': `${BIRKO_SRC}/Birko.Web.Components/src/form-utils/index.ts`,
  'birko-web-shell':       `${BIRKO_SRC}/Birko.Web.Shell/src/index.ts`,
};

// Copy base + theme CSS so <link> and the token editor can read them.
function copyCss() {
  mkdirSync('wwwroot/css', { recursive: true });
  copyFileSync(`${BIRKO_SRC}/Birko.Web.Components/css/tokens.css`, 'wwwroot/css/tokens.css');
  copyFileSync(`${BIRKO_SRC}/Birko.Web.Components/css/reset.css`,  'wwwroot/css/reset.css');
  const themesDir = `${BIRKO_SRC}/Birko.Web.Components/css/themes`;
  if (existsSync(themesDir)) {
    mkdirSync('wwwroot/css/themes', { recursive: true });
    for (const f of readdirSync(themesDir)) {
      if (f.endsWith('.css')) copyFileSync(`${themesDir}/${f}`, `wwwroot/css/themes/${f}`);
    }
  }
}

const options = {
  entryPoints: ['src/app.ts'],
  bundle: true,
  outfile: 'wwwroot/app.js',
  format: 'esm',
  target: 'es2022',
  sourcemap: true,
  alias: aliases,
  loader: { '.ts': 'ts', '.css': 'text' },
  logLevel: 'info',
};

// PWA: a minimal manifest + icon so the playground is installable and its service worker (below,
// generated by the framework's build-sw helper) can be reviewed — install, offline shell, cache prune.
function writePwaAssets() {
  writeFileSync('wwwroot/icon.svg',
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="96" fill="#3b82f6"/>' +
    '<text x="256" y="352" font-size="320" font-family="system-ui,sans-serif" font-weight="700" fill="#fff" text-anchor="middle">B</text></svg>');
  writeFileSync('wwwroot/manifest.webmanifest', JSON.stringify({
    name: 'Birko.Web Playground', short_name: 'Birko PG',
    start_url: '/', display: 'standalone', background_color: '#f3f3f3', theme_color: '#3b82f6',
    icons: [{ src: 'icon.svg', sizes: 'any', type: 'image/svg+xml' }],
  }, null, 2));
}

// The framework PWA build helper (TASK-035 backport) — imported by file URL since BIRKO_SRC is resolved
// at runtime. Emits wwwroot/sw.js with a cache version hashed over the shell assets.
const { writeServiceWorker, serviceWorkerPlugin } = await import(
  pathToFileURL(resolve(BIRKO_SRC, 'Birko.Web.Core/pwa/build-sw.mjs')).href
);
const swOptions = {
  outDir: 'wwwroot',
  cachePrefix: 'birko-playground',
  shellAssets: ['index.html', 'app.js', 'css/tokens.css', 'css/reset.css', 'manifest.webmanifest', 'icon.svg'],
};

copyCss();
copyFileSync('index.html', 'wwwroot/index.html'); // wwwroot is the self-contained web root
writePwaAssets();
if (WATCH) {
  options.plugins = [serviceWorkerPlugin(swOptions)]; // re-stamp the SW after every rebuild
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log(`watching src/ … (BIRKO_SRC=${BIRKO_SRC})`);
} else {
  await esbuild.build(options);
  writeServiceWorker(swOptions);
  console.log(`✓ Built + service worker (BIRKO_SRC=${BIRKO_SRC})`);
}
