// esbuild build for the Birko.Web Playground.
//
// Bundles src/app.ts -> wwwroot/app.js and copies the Birko base CSS into wwwroot/css/.
//
// The checkout resolution and the alias map live in `birko-src.mjs`, because this is no longer their
// only caller: `theme-roundtrip-check.mjs` bundles a throwaway consumer against the same sources, and
// two copies of "which Birko\Web am I testing?" is how they come to disagree.
import * as esbuild from 'esbuild';
import { existsSync, mkdirSync, copyFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { resolveBirkoWeb, birkoAliases } from './birko-src.mjs';

const BIRKO_SRC = resolveBirkoWeb();
const WATCH = process.argv.includes('--watch');

const aliases = birkoAliases(BIRKO_SRC);

// Copy base + theme CSS so <link> and the token editor can read them.
function copyCss() {
  mkdirSync('wwwroot/css', { recursive: true });
  copyFileSync(`${BIRKO_SRC}/Birko.Web.Components/css/tokens.css`, 'wwwroot/css/tokens.css');
  copyFileSync(`${BIRKO_SRC}/Birko.Web.Components/css/reset.css`,  'wwwroot/css/reset.css');
  const themesDir = `${BIRKO_SRC}/Birko.Web.Components/css/themes`;
  if (existsSync(themesDir)) {
    mkdirSync('wwwroot/css/themes', { recursive: true });
    for (const f of readdirSync(themesDir)) {
      if (f.endsWith('.css')) copyFileSync(`${themesDir}/${f}`, `wwwroot/css/themes/${f}`);
    }
  }
}

// A published build minifies and drops the source map; a local one does neither, because the whole
// point of the playground is that you can read the framework source you are looking at in devtools.
// Set by the Pages workflow, never by `npm run build`/`watch`.
const RELEASE = process.argv.includes('--release') || process.env.BIRKO_RELEASE === '1';

const options = {
  entryPoints: ['src/app.ts'],
  bundle: true,
  outfile: 'wwwroot/app.js',
  format: 'esm',
  target: 'es2022',
  minify: RELEASE,
  sourcemap: !RELEASE,
  alias: aliases,
  loader: { '.ts': 'ts', '.css': 'text' },
  logLevel: 'info',
};

// PWA: a minimal manifest + icon so the playground is installable and its service worker (below,
// generated by the framework's build-sw helper) can be reviewed — install, offline shell, cache prune.
function writePwaAssets() {
  writeFileSync('wwwroot/icon.svg',
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="96" fill="#3b82f6"/>' +
    '<text x="256" y="352" font-size="320" font-family="system-ui,sans-serif" font-weight="700" fill="#fff" text-anchor="middle">B</text></svg>');
  writeFileSync('wwwroot/manifest.webmanifest', JSON.stringify({
    name: 'Birko.Web Playground', short_name: 'Birko PG',
    // './' rather than '/': installed from a project GitHub Page the app lives at a subpath, and a
    // root start_url would launch the installed app at the wrong place (or at somebody else's page).
    start_url: './', display: 'standalone', background_color: '#f3f3f3', theme_color: '#3b82f6',
    icons: [{ src: 'icon.svg', sizes: 'any', type: 'image/svg+xml' }],
  }, null, 2));
}

// The framework PWA build helper (TASK-035 backport) — imported by file URL since BIRKO_SRC is resolved
// at runtime. Emits wwwroot/sw.js with a cache version hashed over the shell assets.
const { writeServiceWorker, serviceWorkerPlugin } = await import(
  pathToFileURL(resolve(BIRKO_SRC, 'Birko.Web.Core/pwa/build-sw.mjs')).href
);
const swOptions = {
  outDir: 'wwwroot',
  cachePrefix: 'birko-playground',
  shellAssets: ['index.html', 'app.js', 'css/tokens.css', 'css/reset.css', 'manifest.webmanifest', 'icon.svg'],
};

copyCss();
copyFileSync('index.html', 'wwwroot/index.html'); // wwwroot is the self-contained web root
writePwaAssets();
if (WATCH) {
  options.plugins = [serviceWorkerPlugin(swOptions)]; // re-stamp the SW after every rebuild
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log(`watching src/ … (BIRKO_SRC=${BIRKO_SRC})`);
} else {
  await esbuild.build(options);
  // A release build emits no map, so a stale one from an earlier dev build would otherwise be
  // deployed: 2.1mb of dead weight that also hands a reader the un-minified source they were not
  // offered.
  if (RELEASE) { try { unlinkSync('wwwroot/app.js.map'); } catch { /* absent is fine */ } }
  writeServiceWorker(swOptions);
  console.log(`✓ Built + service worker (BIRKO_SRC=${BIRKO_SRC})`);
}
